<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="78950" started-at="2016-07-16T17:47:53Z" finished-at="2016-07-16T17:49:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="78950" started-at="2016-07-16T17:47:53Z" finished-at="2016-07-16T17:49:12Z">
      <class name="Testcases.VerifyHomePage">
        <test-method status="PASS" signature="setupReport()[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="setupReport" is-config="true" duration-ms="1173" started-at="2016-07-16T23:17:52Z" finished-at="2016-07-16T23:17:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupReport -->
        <test-method status="PASS" signature="startBrowser(java.lang.String)[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="startBrowser" is-config="true" duration-ms="64705" started-at="2016-07-16T23:17:53Z" finished-at="2016-07-16T23:18:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="verifyAccountLink()[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="verifyAccountLink" duration-ms="10526" started-at="2016-07-16T23:18:58Z" finished-at="2016-07-16T23:19:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Pages.LoginPage.LoginToApplication(LoginPage.java:57)
	at Testcases.VerifyHomePage.verifyAccountLink(VerifyHomePage.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountLink -->
        <test-method status="PASS" signature="tearDownReport(org.testng.ITestResult)[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="tearDownReport" is-config="true" duration-ms="1099" started-at="2016-07-16T23:19:08Z" finished-at="2016-07-16T23:19:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyAccountLink status=FAILURE method=VerifyHomePage.verifyAccountLink()[pri:0, instance:Testcases.VerifyHomePage@e580929] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="tearDown" is-config="true" duration-ms="2541" started-at="2016-07-16T23:19:09Z" finished-at="2016-07-16T23:19:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="closeAll()[pri:0, instance:Testcases.VerifyHomePage@e580929]" name="closeAll" is-config="true" duration-ms="700" started-at="2016-07-16T23:19:12Z" finished-at="2016-07-16T23:19:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAll -->
      </class> <!-- Testcases.VerifyHomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
